- project:
    templates:
      - openstack-python-jobs
      - libec-pyeclib-jobs-arm64
      - build-openstack-docs-pti
    check:
      jobs:
        - pyeclib-build-wheels
        - test-release-openstack: &release_overrides
            vars:
              build_wheel: false
        - openstack-tox-py35: &py35_overrides
            vars:
              tox_envlist: py35-compilelibs
              tox_environment:
                LIBERASURECODE_REF: '1.4.0'
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - openstack-tox-py313
        - pyeclib-tox-py39-centos-9-stream
        - libec-pyeclib-unit
        - libec-pyeclib-unit-centos-9-stream
    gate:
      jobs:
        - test-release-openstack: *release_overrides
        - openstack-tox-py35: *py35_overrides
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - pyeclib-tox-py39-centos-9-stream
        - libec-pyeclib-unit
        - libec-pyeclib-unit-centos-9-stream
    pre-release:
      jobs:
        - release-openstack-python: *release_overrides
    release:
      jobs:
        - release-openstack-python: *release_overrides

- job:
    name: pyeclib-tox-py39-centos-9-stream
    parent: openstack-tox-py39
    description: |
      Run unit tests using ``py39`` environment on CentOS 9.
    nodeset: centos-9-stream

- job:
    name: libec-pyeclib-unit-centos-9-stream
    parent: openstack-tox-py39
    timeout: 1800
    nodeset: centos-9-stream
    vars:
      tox_envlist: py39-compilelibs

- job:
    name: libec-pyeclib-unit
    parent: openstack-tox-py312
    timeout: 1800
    vars:
      tox_envlist: py312-compilelibs

- job:
    name: pyeclib-build-wheels
    nodeset: ubuntu-noble
    description: |
      Build binary manylinux wheels that include ISA-L for x86_64.
    pre-run: tools/playbooks/build-wheel/pre.yaml
    run: tools/playbooks/build-wheel/run.yaml
    post-run: tools/playbooks/build-wheel/post.yaml

- job:
    name: libec-pyeclib-unit-arm64
    parent: libec-pyeclib-unit
    nodeset: ubuntu-noble-arm64
    description: |
      Run unit tests for an OpenStack Python project under cPython
      version 3.12 on top of arm64 architecture.

- project-template:
    name: libec-pyeclib-jobs-arm64
    description: |
      Runs pyeclib unit tests designated for testing on top of
      ARM64 architecture
    check-arm64:
      jobs:
        - libec-pyeclib-unit-arm64
