- project:
    templates:
      - openstack-python3-jobs
      - libec-pyeclib-jobs-arm64
      - build-openstack-docs-pti
    check:
      jobs:
        - pyeclib-build-wheels
        - pyeclib-build-wheels-arm64
        - test-release-openstack: &release_overrides
            dependencies:
              - pyeclib-build-wheels
              - pyeclib-build-wheels-arm64
            pre-run: tools/playbooks/release-wheel/download-artifacts.yaml
            vars:
              build_wheel: false
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - openstack-tox-py313
        - pyeclib-tox-py311-centos-9-stream
        - libec-pyeclib-unit
        - libec-pyeclib-unit-centos-9-stream
    gate:
      jobs:
        - pyeclib-build-wheels
        - pyeclib-build-wheels-arm64
        - test-release-openstack: *release_overrides
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - openstack-tox-py313
        - pyeclib-tox-py311-centos-9-stream
        - libec-pyeclib-unit
        - libec-pyeclib-unit-centos-9-stream
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            vars:
              build_wheel: false
    pre-release:
      jobs:
        - pyeclib-build-wheels
        - pyeclib-build-wheels-arm64
        - release-openstack-python: *release_overrides
    release:
      jobs:
        - pyeclib-build-wheels
        - pyeclib-build-wheels-arm64
        - release-openstack-python: *release_overrides

- job:
    name: pyeclib-tox-py311-centos-9-stream
    parent: openstack-tox-py311
    description: |
      Run unit tests using ``py311`` environment on CentOS 9.
    nodeset: centos-9-stream
    vars:
      python_use_pyenv: true

- job:
    name: libec-pyeclib-unit-centos-9-stream
    parent: openstack-tox-py311
    timeout: 1800
    nodeset: centos-9-stream
    vars:
      python_use_pyenv: true
      tox_envlist: py311-compilelibs

- job:
    name: libec-pyeclib-unit
    parent: openstack-tox-py312
    timeout: 1800
    vars:
      tox_envlist: py312-compilelibs

- job:
    name: pyeclib-build-wheels
    nodeset: ubuntu-noble
    description: |
      Build binary manylinux wheels that include ISA-L for x86_64.
    pre-run: tools/playbooks/build-wheel/pre.yaml
    run: tools/playbooks/build-wheel/run.yaml
    post-run: tools/playbooks/build-wheel/post.yaml

- job:
    name: pyeclib-build-wheels-arm64
    parent: pyeclib-build-wheels
    timeout: 3600
    nodeset: ubuntu-noble-arm64
    description: |
      Build binary manylinux wheels that include ISA-L for ARM64.
    vars:
      wheel_target: aarch64

- job:
    name: libec-pyeclib-unit-arm64
    parent: libec-pyeclib-unit
    nodeset: ubuntu-noble-arm64
    description: |
      Run unit tests for an OpenStack Python project under cPython
      version 3.12 on top of arm64 architecture.

- project-template:
    name: libec-pyeclib-jobs-arm64
    description: |
      Runs pyeclib unit tests designated for testing on top of
      ARM64 architecture
    check-arm64:
      jobs:
        - libec-pyeclib-unit-arm64
