- hosts: all
  tasks:
    - name: Find wheels
      find:
        file_type: file
        paths: '{{ ansible_user_dir }}/artifacts'
        patterns: "*.whl"
      register: result

    - name: Copy wheels for upload
      synchronize:
        src: '{{ ansible_user_dir }}/artifacts'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        verify_host: true

    - name: Return wheels to Zuul
      loop: '{{ result.files }}'
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: '{{ item.path | basename }}'
                url: 'artifacts/{{ item.path | basename }}'
                metadata:
                  type: python_wheel
                  # TODO: parse further metadata from basename (python tag, ABI tag)
