- hosts: all
  tasks:
    - name: Find wheels
      find:
        file_type: file
        paths: '{{ ansible_user_dir }}/artifacts'
        patterns: "*.whl"
      register: result

    - name: Copy wheels for upload
      synchronize:
        src: '{{ ansible_user_dir }}/artifacts'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        verify_host: true

    - name: Return wheels to Zuul
      loop: '{{ result.files }}'
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: '{{ item.path | basename }}'
                url: 'artifacts/{{ item.path | basename }}'
                metadata:
                  type: python_wheel
                  package: '{{ (item.path | basename | split("-") ).0 }}'
                  version: '{{ (item.path | basename | split("-") ).1 }}'
                  # according to https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/
                  # there may or may not be a "build tag" next, whatever that is
                  python-tag: '{{ (item.path | basename | split("-") )[-3] }}'
                  abi-tag: '{{ (item.path | basename | split("-") )[-2] }}'
                  platform-tag: '{{ (item.path[:-4] | basename | split("-") )[-1].split(".") }}'
