- hosts: all
  roles:
    - build-pyeclib-image

    - role: build-pyeclib-wheel
      wheel_python_version: cp27-cp27m
      when: wheel_target != "aarch64"

    - role: build-pyeclib-wheel
      wheel_python_version: cp27-cp27mu
      when: wheel_target != "aarch64"

    - role: build-pyeclib-wheel
      wheel_python_version: cp35-cp35m
