- name: Build wheel
  command: >
    docker run --rm
    --env PYTHON_VERSION={{ wheel_python_version }}
    --volume {{ ansible_user_dir }}/artifacts:/output:Z
    {{ tag }}{{ "-musl" if musl else "" }}
